import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar2 from "../components/SideBar2";
import { ReduxProvider } from "../redux/Provider";
import PageWrapper from "../components/WrapperPage";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <ReduxProvider>
                    <div className="flex">
                        <SideBar2 />
                        <PageWrapper>{children}</PageWrapper>
                    </div>
                </ReduxProvider>
            </body>
        </html>
    );
}
